### ISSUE TITLE
`npm install` fails with "TypeError: Request path contains unescaped characters."

### ISSUE THREAD

**Issue by eighthave** [facundoolano/google-play-scraper#146]
On a Debian/stretch chroot, I did `apt install npm` which gave me npm (1.4.21+ds-2) and nodejs (4.7.2~dfsg-2), as well as lots of node.js libraries.  Then I ran `npm install google-play-scraper` as a regular user, and got:

```
$ npm install google-play-scraper
npm ERR! TypeError: Request path contains unescaped characters.
npm ERR!     at new ClientRequest (_http_client.js:50:11)
npm ERR!     at TunnelingAgent.exports.request (http.js:31:10)
npm ERR!     at TunnelingAgent.createSocket (/usr/lib/nodejs/tunnel-agent/index.js:117:25)
npm ERR!     at TunnelingAgent.createSecureSocket [as createSocket] (/usr/lib/nodejs/tunnel-agent/index.js:184:41)
npm ERR!     at TunnelingAgent.addRequest (/usr/lib/nodejs/tunnel-agent/index.js:80:8)
npm ERR!     at new ClientRequest (_http_client.js:142:16)
npm ERR!     at Object.exports.request (http.js:31:10)
npm ERR!     at Object.socket.once.exports.request (https.js:182:15)
npm ERR!     at Request.start (/usr/lib/nodejs/request/index.js:607:30)
npm ERR!     at Request.end (/usr/lib/nodejs/request/index.js:1235:28)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.4.0-67-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "google-play-scraper"
npm ERR! cwd /home/hans
npm ERR! node -v v4.7.2
npm ERR! npm -v 1.4.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/hans/npm-debug.log
npm ERR! not ok code 0
```

[npm-debug.log.zip](https://github.com/facundoolano/google-play-scraper/files/857984/npm-debug.log.zip)

**Comment by eighthave** [comment]
sorry for the noise, the bug is elsewhere.
