### ISSUE TITLE
SyntaxError:  Use of const in strict mode. & Unexpected token >

### ISSUE THREAD

**Issue by michaelcmundo** [facundoolano/google-play-scraper#214]
I got the following error when running your example code. The first one I can by pass when I do node --harmony but the 2nd one I'm not sure. Is there bug? How can I get it to run?

/google-play-scraper/node_modules/google-play-scraper/index.js:3
const R = require('ramda');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/google-play-scraper/test.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

]# node --harmony test.js

/google-play-scraper/node_modules/google-play-scraper/index.js:31
  const doMemoize = (fn) => memoizee(fn, cacheOpts);
                          ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/google-play-scraper/test.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by michaelcmundo** [comment]
I tested it on v0.10.46

What is the min ver this need?

**Comment by facundoolano** [comment]
I honestly don't know, and I'm not sure how to find out easily, but for sure 0.10 is not supported (that version is 5 years old). This needs ES6 features (arrow functions, let, const), I suggest trying node 6 or node 8.

For reference: 
https://github.com/nodejs/Release
http://node.green/
