### ISSUE TITLE
store.scores fails with "Cannot read property 'replace' of undefined"

### ISSUE THREAD

**Issue by ftcvlad** [facundoolano/google-play-scraper#241]
* google-play-scraper version: 6.0.0

related issue is https://github.com/facundoolano/google-play-scraper/issues/192. I think google might have changed shape of the data again.

This fail is due to "description" field (see below), but it also fails for some other fields

```
const MAPPINGS = {
  // FIXME add appId

  title: ['ds:3', 0, 0, 0],
  description: {
    path: ['ds:3', 0, 10, 0, 1], //<--- path incorrect
    fun: descriptionText
  },
.....
}
```

```
TypeError: Cannot read property 'replace' of undefined
    at Object.descriptionText [as fun] (/Users/vvoicehovics/project/app-delivery/aso-lookup-service/node_modules/google-play-scraper/lib/app.js:182:50)
    at R.map (/Users/vvoicehovics/project/app-delivery/aso-lookup-service/node_modules/google-play-scraper/lib/app.js:176:17)
    at XWrap.f (/Users/vvoicehovics/project/app-delivery/aso-lookup-service/node_modules/ramda/dist/ramda.js:5955:28)
    at XWrap.@@transducer/step (/Users/vvoicehovics/project/app-delivery/aso-lookup-service/node_modules/ramda/dist/ramda.js:392:25)
    at _arrayReduce (/Users/vvoicehovics/project/app-delivery/aso-lookup-service/node_modules/ramda/dist/ramda.js:5137:46)
    at _reduce (/Users/vvoicehovics/project/app-delivery/aso-lookup-service/node_modules/ramda/dist/ramda.js:5167:24)
    at map (/Users/vvoicehovics/project/app-delivery/aso-lookup-service/node_modules/ramda/dist/ramda.js:5954:20)
    at /Users/vvoicehovics/project/app-delivery/aso-lookup-service/node_modules/ramda/dist/ramda.js:586:23
    at Object.f2 [as map] (/Users/vvoicehovics/project/app-delivery/aso-lookup-service/node_modules/ramda/dist/ramda.js:473:22)
    at extractFields (/Users/vvoicehovics/project/app-delivery/aso-lookup-service/node_modules/google-play-scraper/lib/app.js:170:12)
```

**Comment by facundoolano** [comment]
Install the latest version.
