### ISSUE TITLE
App Data Scraping: Cannot read property 'split' of undefined.

### ISSUE THREAD

**Issue by AdamSlack** [facundoolano/google-play-scraper#244]
* Operating System: Ubuntu 16.04
* Node version: v10.4.1
* google-play-scraper version: Old... 3.x.x

Hey, I'm getting some errors when running some code from about a year ago that made use of your scraper, i'm just wondering if there has been any major changes since last summer that might cause it to break.

### Error message:

The error that i'm getting:
```
(node:12615) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
at parseFields (<REDACTED>/node_modules/google-play-scraper/lib/app.js:49:64)
at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Example code:
```
gplay.app({appId:'com.facebook.orca'}).then(res=>console.log(res));
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events:
      { removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [] } }
```

**Comment by AdamSlack** [comment]
Sorry, turns out the version was 3 releases old! updated and it seems to be fine now :+1:
