### ISSUE TITLE
Error using aso

### ISSUE THREAD

**Issue by AdityaAnand1** [facundoolano/google-play-scraper#245]
I'm getting the following error when using the aso repo, seems like something in google-play-scraper

```

(node:4660) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at parseFields (C:\Dev\Node\node_modules\google-play-scraper\lib\app.js:49:64)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:4660) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4660) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

My package.json:

```
{
  "name": "aso_project",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "aso": "1.0.0"
  }
}

```

My index.js

```
const gplay = require('aso')('gplay');
gplay.scores('keyword').then(console.log);

```

I'm on Windows. Any idea as to what's going on?

**Comment by facundoolano** [comment]
Already reported in the ASO project.
