### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined with 6.1.0

### ISSUE THREAD

**Issue by mdbijlise** [facundoolano/google-play-scraper#246]
TypeError: Cannot read property 'replace' of undefined
    at Object.descriptionText [as fun] (/app/node_modules/google-play-scraper/lib/app.js:178:51)
    at R.map (/app/node_modules/google-play-scraper/lib/app.js:172:17)
    at XWrap.f (/app/node_modules/ramda/dist/ramda.js:5955:28)
    at XWrap.@@transducer/step (/app/node_modules/ramda/dist/ramda.js:392:25)
    at _arrayReduce (/app/node_modules/ramda/dist/ramda.js:5137:46)
    at _reduce (/app/node_modules/ramda/dist/ramda.js:5167:24)
    at map (/app/node_modules/ramda/dist/ramda.js:5954:20)
    at /app/node_modules/ramda/dist/ramda.js:586:23
    at Object.f2 [as map] (/app/node_modules/ramda/dist/ramda.js:473:22)
    at extractFields (/app/node_modules/google-play-scraper/lib/app.js:166:12)
Fetched Android ratings trough Scraping: 217.965ms

**Comment by mdbijlise** [comment]
I was wrong with the version, sorry about that. It's working in 6.1.0
