### ISSUE TITLE
can not scrap data from google play store

### ISSUE THREAD

**Issue by amanritesh94** [facundoolano/google-play-scraper#289]
* google-play-scraper version:
 "google-play-scraper": "^6.2.2"
### Description: 
i am trying to scrap data from play store by providing appid.
it was working properly but from today i am facing the issue

### Example code:
```js
// Put code to reproduce the issue here
```const googlePlay = await gplay.app({ appId: args.packageName })
                    .then(docs => {
                        if (docs) {
                            return { docs }

                        }
                        console.log(docs);
                    });

### Error message:
(node:7993) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at Object.descriptionText [as fun] (/home/ritu/nodejs-appified/node_modules/google-play-scraper/lib/app.js:181:51)
    at R.map (/home/ritu/nodejs-appified/node_modules/google-play-scraper/lib/app.js:175:17)
    at XWrap.f (/home/ritu/nodejs-appified/node_modules/ramda/dist/ramda.js:5955:28)
    at XWrap.@@transducer/step (/home/ritu/nodejs-appified/node_modules/ramda/dist/ramda.js:392:25)
    at _arrayReduce (/home/ritu/nodejs-appified/node_modules/ramda/dist/ramda.js:5137:46)
    at _reduce (/home/ritu/nodejs-appified/node_modules/ramda/dist/ramda.js:5167:24)
    at map (/home/ritu/nodejs-appified/node_modules/ramda/dist/ramda.js:5954:20)
    at /home/ritu/nodejs-appified/node_modules/ramda/dist/ramda.js:586:23
    at Object.f2 [as map] (/home/ritu/nodejs-appified/node_modules/ramda/dist/ramda.js:473:22)
    at extractFields (/home/ritu/nodejs-appified/node_modules/google-play-scraper/lib/app.js:169:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:7993) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7993) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:7993) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at Object.descriptionText [as fun] (/home/ritu/nodejs-appified/node_modules/google-play-scraper/lib/app.js:181:51)
    at R.map (/home/ritu/nodejs-appified/node_modules/google-play-scraper/lib/app.js:175:17)
    at XWrap.f (/home/ritu/nodejs-appified/node_modules/ramda/dist/ramda.js:5955:28)
    at XWrap.@@transducer/step (/home/ritu/nodejs-appified/node_modules/ramda/dist/ramda.js:392:25)
    at _arrayReduce (/home/ritu/nodejs-appified/node_modules/ramda/dist/ramda.js:5137:46)
    at _reduce (/home/ritu/nodejs-appified/node_modules/ramda/dist/ramda.js:5167:24)
    at map (/home/ritu/nodejs-appified/node_modules/ramda/dist/ramda.js:5954:20)
    at /home/ritu/nodejs-appified/node_modules/ramda/dist/ramda.js:586:23
    at Object.f2 [as map] (/home/ritu/nodejs-appified/node_modules/ramda/dist/ramda.js:473:22)
    at extractFields (/home/ritu/nodejs-appified/node_modules/google-play-scraper/lib/app.js:169:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:7993) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:7993) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at Object.descriptionText [as fun] (/home/ritu/nodejs-appified/node_modules/google-play-scraper/lib/app.js:181:51)
    at R.map (/home/ritu/nodejs-appified/node_modules/google-play-scraper/lib/app.js:175:17)
    at XWrap.f (/home/ritu/nodejs-appified/node_modules/ramda/dist/ramda.js:5955:28)
    at XWrap.@@transducer/step (/home/ritu/nodejs-appified/node_modules/ramda/dist/ramda.js:392:25)
    at _arrayReduce (/home/ritu/nodejs-appified/node_modules/ramda/dist/ramda.js:5137:46)
    at _reduce (/home/ritu/nodejs-appified/node_modules/ramda/dist/ramda.js:5167:24)
    at map (/home/ritu/nodejs-appified/node_modules/ramda/dist/ramda.js:5954:20)
    at /home/ritu/nodejs-appified/node_modules/ramda/dist/ramda.js:586:23
    at Object.f2 [as map] (/home/ritu/nodejs-appified/node_modules/ramda/dist/ramda.js:473:22)
    at extractFields (/home/ritu/nodejs-appified/node_modules/google-play-scraper/lib/app.js:169:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:7993) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

```
Put error message here
```

**Comment by gdimoff** [comment]
Yep there is update on the Google side, so this needs to be fixed in the scraper ! Hope to get it fixed soon !

Keep the good working going !

**Comment by ansonete** [comment]
Same issue here

**Comment by vitaliy901** [comment]
same  issue ((

**Comment by bbyojjok** [comment]
same issue ~

**Comment by vitaliy901** [comment]
maybe someone could fix this error & pull up fix ?

**Comment by hubingliang** [comment]
same issue + 1 !

**Comment by almtwer** [comment]
Same issue here
please fix it ASAP

**Comment by yurganov** [comment]
@almtwer, you know what mean opensource, right?

**Comment by yangyangFE** [comment]
I have fixed some fields. but there are some fields I don't know the means, My pull request is fail.

**Comment by yurganov** [comment]
https://github.com/facundoolano/google-play-scraper/pull/290

**Comment by facundoolano** [comment]
I merged @yurganov PR and published a new version. This should be fixed now.

**Comment by yurganov** [comment]
Thanks!

But it was @yangyangFE PR

I was 5 minutes late :-D
