### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by Joepruner** [facundoolano/google-play-scraper#314]
* Operating System: Linux Mint 19 Tara
* Node version: v10.15.3
* google-play-scraper version: 6.9.0

### Description: 
I am suddenly getting "Unhandled rejection TypeError: Cannot read property 'map' of undefined". I am receiving this error from multiple files that have been unchanged, and were working fine 2 days ago.

Thank you for any help you can offer.
-Joe

### Example code:
```
const gplay = require('google-play-scraper');
const fs = require('fs');
// const csv = require('csv-parser');
const Json2csvParser = require('json2csv').Parser;
const csvtojson = require('csvtojson');

const fields = ['appTitle', 'userName', 'date', 'score', 'text'];

const opts = {
    'header': false
};

const json2csvParserApps = new Json2csvParser();
const json2csvParserReviewsRest = new Json2csvParser(opts);
const json2csvParserReviewsFirst = new Json2csvParser({
    fields
});

var today = new Date();
var date = today.getFullYear() + '-' + (today.getMonth() + 1) + '-' + today.getDate();

var titles_input_path = '../../input_data/worst_mod_app_titles.csv';
var external_apps_output_path = '/home/joepruner/Projects/GooglePlayScraper/output_data/test_output/' + date + '_app_details_';
var external_reviews_output_path = '/home/joepruner/Projects/GooglePlayScraper/output_data/test_output/' + date + '_reviews_';

var apps_output_stream = fs.createWriteStream(external_apps_output_path, {
    encoding: 'utf8'
});
var reviews_output_stream = fs.createWriteStream(external_reviews_output_path, {
    encoding: 'utf8',
    flags: 'a'
});

/**
 * Returns JSON array of full app details from the first (or more) search result(s),
 * based on the app title search term.
 * @param {string} at - The title of the app being searched for.
 */
var getAppDetails = function getAppDetails(at) { // sample async action
    // console.log(at['title']);
    return new Promise(resolve => setTimeout(() => resolve(
        gplay.search({
            term: at['title'],
            num: 1,
            fullDetail: true,
            throttle: 2
        })), 100));
};

/**
 * Returns array of JSON for a single page of reviews for appId.
 * @param {string} aid - The app id to get reviews for.
 * @param {int} num - The review page number.
 * @param {string} appTitle - Used to add an appTitle field to the JSON obj
 * returned from gplay.reviews. NOT used for searching for app.
 */
var getAppReviews = function getAppReviews(aid, num, appTitle, timeout) {
    // console.log(appTitle);
    return new Promise(resolve => setTimeout(() => resolve(
        gplay.reviews({
            appId: aid,
            page: num,
            sort: gplay.sort.RATING,
            throttle: 3
        }, appTitle)), timeout));
};
function getRndInteger(min, max) {
    return Math.floor(Math.random() * (max - min)) + min;
}
csvtojson()
    .fromFile(titles_input_path)
    .then((titles) => {

        var pending_getAppDetails_promise = titles.map(getAppDetails);
        var resolved_getAppDetails_promise = Promise.all(pending_getAppDetails_promise);
        // console.log(titles);
        return resolved_getAppDetails_promise;
    }).then(function (appDetails) {

        var num_titles = Object.keys(appDetails).length;

        for (var i = 0; i < num_titles; i++) {
            var parsed_app_details = json2csvParserApps.parse(appDetails[i]);
            apps_output_stream.write(parsed_app_details);
        }

        var parsed_headers = json2csvParserReviewsFirst.parse();
        reviews_output_stream.write(parsed_headers);
        reviews_output_stream.write('\n');

        appDetails.forEach(app => {
            for (var i = 0; i < 112; i++) {

                getAppReviews(app[0].appId, i, app[0].title, i * 1.7).then(function (review) {
                    if (review.length < 1 || review == undefined) {
                        return false;
                    }

                    var parsed_app_reviews = json2csvParserReviewsRest.parse(review);
                    reviews_output_stream.write(parsed_app_reviews);
                    reviews_output_stream.write('\n');
                });
            }
        });
    });
```
### Error message:

```
Unhandled rejection TypeError: Cannot read property 'map' of undefined
    at /home/joepruner/Projects/GooglePlayScraper/node_modules/ramda/dist/ramda.js:578:31
    at Object.f2 [as map] (/home/joepruner/Projects/GooglePlayScraper/node_modules/ramda/dist/ramda.js:473:22)
    at Object.extract (/home/joepruner/Projects/GooglePlayScraper/node_modules/google-play-scraper/lib/utils/appList.js:44:12)
    at processAndRecur (/home/joepruner/Projects/GooglePlayScraper/node_modules/google-play-scraper/lib/search.js:19:24)
    at request.then.then (/home/joepruner/Projects/GooglePlayScraper/node_modules/google-play-scraper/lib/search.js:74:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by Joepruner** [comment]
This error has stopped on it's own with no changes to code.

**Comment by Parth2404** [comment]
Hi there, 

This issue seems to have popup again.

**Description**
When trying to get score for particular keyword it just crashes.

**Code**
<code>
const gplay = require('aso')('gplay');

// do stuff with google play
gplay.scores('panda').then(console.log);
</code>

**Error**
<code>TypeError: Cannot read property 'map' of undefined
    at /home/hardik/Desktop/test/ASO project/node_modules/ramda/dist/ramda.js:578:31
    at Object.f2 [as map] (/home/hardik/Desktop/test/ASO project/node_modules/ramda/dist/ramda.js:473:22)
    at Object.extract (/home/hardik/Desktop/test/ASO project/node_modules/aso/node_modules/google-play-scraper/lib/utils/appList.js:44:12)
    at processAndRecur (/home/hardik/Desktop/test/ASO project/node_modules/aso/node_modules/google-play-scraper/lib/search.js:19:24)
    at /home/hardik/Desktop/test/ASO project/node_modules/aso/node_modules/google-play-scraper/lib/search.js:74:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5)</code>
