### ISSUE TITLE
 Cannot read property 'topselling_free'

### ISSUE THREAD

**Issue by loadingpix** [facundoolano/google-play-scraper#342]
Using the aso package shows an error:

I'm using the 7.00 version of scrapper.

```
 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'topselling_free' of undefined
    at getParsedCluster (C:\Users\user\node_modules\aso\node_modules\google-play-scraper\lib\utils\parseCategoryApps.js:41:63)
    at parseCategoryApps (C:\Users\user\node_modules\aso\node_modules\google-play-scraper\lib\utils\parseCategoryApps.js:60:22)
    at request.then.then.parsedObject (C:\Users\user\node_modules\aso\node_modules\google-play-scraper\lib\list.js:24:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:16208) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16208) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

Any workaround?

**Comment by icarcal** [comment]
Hey @loadingpix can you provide a code sample so we can reproduce the error?

**Comment by loadingpix** [comment]
> Hey @loadingpix can you provide a code sample so we can reproduce the error?
@icarcal  Sorry by bad, my workaround was installing version 7.00 and copy the google-play-scrapper folder to inside of aso/node_modules.

@facundoolano aso package needs to use this latest version to work. (Difficulty scores are broken too).

Thank you,
problem solved.
