### ISSUE TITLE
Error "Unexpected token function" when running sample code

### ISSUE THREAD

**Issue by xulifan** [facundoolano/google-play-scraper#347]
* Operating System: Ubuntu 16
* Node version: 6.17.1
* google-play-scraper version: 7.0.1

### Description: 
Just trying to run the example code to get app details, but returned following error.

### Example code:
```
var gplay = require('google-play-scraper');

gplay.app({appId: 'com.dxco.pandavszombies'})
  .then(console.log, console.log);
```

### Error message:

```
/home/lxu/github_remote/test/node_modules/google-play-scraper/lib/requesters/appsMappedRequests.js:21
async function processFullDetailApps (apps, opts) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/lxu/github_remote/test/node_modules/google-play-scraper/lib/utils/parseCategoryApps.js:9:29)
```

**Comment by facundoolano** [comment]
your node version is outdated

**Comment by vipinhelloindia** [comment]
![error](https://user-images.githubusercontent.com/700307/65326351-dc765800-dbce-11e9-87b0-c87a34d3facd.png)

**Comment by icarcal** [comment]
@vipinhelloindia
Probably you bash is still using an old version of node.
Can you please double check your version of node running the `node -v` command?
