### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined in Gplay.Permissions

### ISSUE THREAD

**Issue by abubakaraziz** [facundoolano/google-play-scraper#356]
* Operating System:Ubuntu 18.04.2 LTS
* Node version:v12.11.0
* google-play-scraper version:6.11.3

I have noticed for many app ids the code gives cannot read property of map undefined. These apps do exist in the play store with their permission. I have checked on both node version 10 and node version 12. Following apps produced the same issue:
1.app.clientell.app
2.mappstreet.fs_soccer
3.com.ebookrenta.en_app
4.air.tv.ingames.cubematch.free
I have also checked that their permissions do exists on the google play store and other gplay methods such as Gplay.apps are working fine with them.

const gPlay=require('./google-play-scraper');

(async()=>{
	try{
		let Permissions=await gPlay.permissions({appId:"air.tv.ingames.cubematch.free"})
		console.log(Permissions)	
	}catch(e) {
		console.log(e)
	console.log("App Not Found")
}

})()

TypeError: Cannot read property 'map' of undefined
at /home/aziz/Network_Security_Project/PPI/iowa_github/ppidatacollection/GPlayCrawler/finalCrawler/google-play-scraper/node_modules/ramda/dist/ramda.js:578:31
    at Object.f2 [as map] (/home/aziz/Network_Security_Project/PPI/iowa_github/ppidatacollection/GPlayCrawler/finalCrawler/google-play-scraper/node_modules/ramda/dist/ramda.js:473:22)
    at Object.extract (/home/aziz/Network_Security_Project/PPI/iowa_github/ppidatacollection/GPlayCrawler/finalCrawler/google-play-scraper/lib/utils/permissionList.js:21:12)
    at flatMapPermissions (/home/aziz/Network_Security_Project/PPI/iowa_github/ppidatacollection/GPlayCrawler/finalCrawler/google-play-scraper/lib/requesters/permissionMappedRequests.js:20:59)
    at _map (/home/aziz/Network_Security_Project/PPI/iowa_github/ppidatacollection/GPlayCrawler/finalCrawler/google-play-scraper/node_modules/ramda/dist/ramda.js:262:27)
    at map (/home/aziz/Network_Security_Project/PPI/iowa_github/ppidatacollection/GPlayCrawler/finalCrawler/google-play-scraper/node_modules/ramda/dist/ramda.js:5959:20)
    at /home/aziz/Network_Security_Project/PPI/iowa_github/ppidatacollection/GPlayCrawler/finalCrawler/google-play-scraper/node_modules/ramda/dist/ramda.js:586:23
    at f2 (/home/aziz/Network_Security_Project/PPI/iowa_github/ppidatacollection/GPlayCrawler/finalCrawler/google-play-scraper/node_modules/ramda/dist/ramda.js:473:22)
    at chain (/home/aziz/Network_Security_Project/PPI/iowa_github/ppidatacollection/GPlayCrawler/finalCrawler/google-play-scraper/node_modules/ramda/dist/ramda.js:6802:33)
    at /home/aziz/Network_Security_Project/PPI/iowa_github/ppidatacollection/GPlayCrawler/finalCrawler/google-play-scraper/node_modules/ramda/dist/ramda.js:586:23
App Not Found

**Comment by icarcal** [comment]
Hey @abubakaraziz 
This is already fixed.

You can check the fix at #340

This package received a breaking change, so be sure to update it to the version 7+

**Comment by abubakaraziz** [comment]
@icarcal I am using the latest git pull and I know about the breaking change. It gets data for the majority of the applications, but for some, it gives map undefined error. Let me download node modules again and check.

**Comment by icarcal** [comment]
@abubakaraziz thanks for letting me know that you are using the 7.0.3 version
And thanks for reporting.
I just checked the error and it is really happening.

I just sent the PR #357
You can check the details there.

**Comment by facundoolano** [comment]
published the patch.

**Comment by abubakaraziz** [comment]
@icarcal Thank you for updating the repo. I really appreciate your work :)
