### ISSUE TITLE
TypeError: Cannot read property 'chain' of null in Permissions method

### ISSUE THREAD

**Issue by abubakaraziz** [facundoolano/google-play-scraper#359]
* Operating System:Ubuntu 18.04.2 LTS
* Node version:v10.16.3
*google-play-scraper version:7.0.4

### Description: 
 I have noticed for many app ids the code gives TypeError: Cannot read property 'chain' of null. 

### Example code:
const gPlay=require('./google-play-scraper');

(async()=>{

	try{
		let Permissions=await gPlay.permissions({appId:"com.skybornegames.battlepop"})
		console.log(Permissions)	
	}catch(e) {
		console.log(e)
	console.log("App Not Found")
}
})()

### Error message:
TypeError: Cannot read property 'chain' of null
    at /home/aziz/Network_Security_Project/PPI/iowa_github/ppidatacollection/GPlayCrawler/finalCrawler/google-play-scraper/node_modules/ramda/dist/ramda.js:578:31
    at Object.f2 [as chain] (/home/aziz/Network_Security_Project/PPI/iowa_github/ppidatacollection/GPlayCrawler/finalCrawler/google-play-scraper/node_modules/ramda/dist/ramda.js:473:22)
    at processPermissionData (/home/aziz/Network_Security_Project/PPI/iowa_github/ppidatacollection/GPlayCrawler/finalCrawler/google-play-scraper/lib/requesters/permissionMappedRequests.js:24:31)
    at request.then (/home/aziz/Network_Security_Project/PPI/iowa_github/ppidatacollection/GPlayCrawler/finalCrawler/google-play-scraper/lib/requesters/permissionMappedRequests.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
App Not Found

**Comment by icarcal** [comment]
@abubakaraziz Thanks for reporting this.
Just sent a PR #361 
You can check the details there.

**Comment by abubakaraziz** [comment]
@icarcal Thanks for fixing it so promptly. I really appreciate that.

**Comment by facundoolano** [comment]
This is fixed in v7.0.5
