### ISSUE TITLE
search  Cannot read property '4' of null

### ISSUE THREAD

**Issue by tonybricheff** [facundoolano/google-play-scraper#420]
* Operating System: MacOS 10.15.6
* Node version: v12.16.1
* google-play-scraper version: 7.1.3

### Description: 
When I am trying to search with full details the app throws TypeError: Cannot read property '4' of null

    
### Example code:
 gplay.search({
            term: "game",
            num: 250,
            fullDetail: true
        }).then(console.log, console.log);

### Error message:
TypeError: Cannot read property '4' of null
at prop (/Users/antonbrichev/Desktop/Node/node_modules/ramda/dist/ramda.js:3399:19)
    at /Users/antonbrichev/Desktop/Node/node_modules/ramda/dist/ramda.js:466:28
    at f1 (/Users/antonbrichev/Desktop/Node/node_modules/ramda/dist/ramda.js:446:27)
    at _map (/Users/antonbrichev/Desktop/Node/node_modules/ramda/dist/ramda.js:262:27)
    at map (/Users/antonbrichev/Desktop/Node/node_modules/ramda/dist/ramda.js:5959:20)
    at /Users/antonbrichev/Desktop/Node/node_modules/ramda/dist/ramda.js:586:23
    at f2 (/Users/antonbrichev/Desktop/Node/node_modules/ramda/dist/ramda.js:473:22)
    at pluck (/Users/antonbrichev/Desktop/Node/node_modules/ramda/dist/ramda.js:6121:16)
    at /Users/antonbrichev/Desktop/Node/node_modules/ramda/dist/ramda.js:466:28
    at f1 (/Users/antonbrichev/Desktop/Node/node_modules/ramda/dist/ramda.js:446:27)

**Comment by icarcal** [comment]
@tonybricheff thanks for reporting.

Google play added a new section in their website:
![Screen Shot 2020-07-20 at 19 38 25](https://user-images.githubusercontent.com/11530480/87993656-6ded7980-cac1-11ea-8ccf-08f5d3d6b6f1.png)

This change conflicts with some mappings (for `us` only), I'll try to figure something out for this.

**Comment by icarcal** [comment]
@tonybricheff #412 was merged today, be sure to update the module to the version 8+

**Comment by 1004885516** [comment]
> @tonybricheff #412今天已合并，请务必将模块更新到版本 8+

await gplay.app({ appId: 'com.hitplay.tpgamesdfsd' })

ERROR 50080 nodejs.TypeError: Cannot read property 'replace' of undefined
