### ISSUE TITLE
Getting Unexpected token error

### ISSUE THREAD

**Issue by JoniChen** [facundoolano/google-play-scraper#433]
OSX Catalina 10.15.5
NPM 6.14.5
play scraper 8.0.1

Nothing changed in my project but all of the sudden im getting error when trying to get app info .
Asking for permission list works 

SyntaxError: Unexpected token , in JSON at position 6038
    at JSON.parse (<anonymous>)
    at matches.reduce (/Users/admin1/WebstormProjects/untitled1/node_modules/google-play-scraper/lib/utils/scriptData.js:78:26)
    at Array.reduce (<anonymous>)
    at parse (/Users/admin1/WebstormProjects/untitled1/node_modules/google-play-scraper/lib/utils/scriptData.js:72:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by facundoolano** [comment]
update the package version
