### ISSUE TITLE
JSON parsing failing for search

### ISSUE THREAD

**Issue by rchatterjee** [facundoolano/google-play-scraper#436]
* Operating System: Linux
* Node version: v8.10.0
* google-play-scraper version: 0.16.3

```bash 
$ npm list | grep scraper
scraper@1.0.0 /nobackup/projects/appscraper/scraper
├─┬ app-store-scraper@0.16.3
├─┬ google-play-scraper@7.1.3
```

### Description: 
The `search` is failing, possibly due to some changes on Google's end. ( I might get back to fix it, but if anyone has time before that.)

### Example code:
```js
var gplay = require('google-play-scraper');
gplay.search({term: 'friends', num: 2}).then(console.log, console.log);
```

### Error message:

```bash
        SyntaxError: Unexpected token , in JSON at position 143
    at JSON.parse (<anonymous>)
    at matches.reduce (/nobackup/projects/appscraper/scraper/node_modules/google-play-scraper/lib/utils/scriptData.js:48:26)
    at Array.reduce (<anonymous>)
    at Object.parse (/nobackup/projects/appscraper/scraper/node_modules/google-play-scraper/lib/utils/scriptData.js:42:18)
    at processAndRecur (/nobackup/projects/appscraper/scraper/node_modules/google-play-scraper/lib/search.js:16:23)
    at request.then.then (/nobackup/projects/appscraper/scraper/node_modules/google-play-scraper/lib/search.js:74:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by facundoolano** [comment]
Your scraper version is old.

**Comment by rchatterjee** [comment]
Oops, sorry. Thanks for the quick response.
