### ISSUE TITLE
Not found similar link at some Korean App - region specific issue with "similar" feature

### ISSUE THREAD

**Issue by miki3475** [facundoolano/google-play-scraper#438]
* Operating System: Windows 10
* Node version: Node.js 12.18.3
* google-play-scraper version: google-play-scraper@7.1.3 + fix with new scriptData.js file

### Description: 
For some reason when scraping similar apps to some Korean app I get error "not found similar link", however when I change id to some English app or any other "similar" to English it works great.

### Example code:
```js
var gplay = require('google-play-scraper');

gplay.similar({appId: 'a.kakao.iconnect.Space.Whale'})
  .then(console.log(), console.log() );
```

### Error message:
```
Error: not found similar link
    at C:\xampp\htdocs\apps\node\node_modules\google-play-scraper\lib\similar.js:37:17
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

However when AppId is changed to any other, like _com.nordvpn.android_ it works great with results. And that one before exist normally on Play Store: https://play.google.com/store/apps/details?id=a.kakao.iconnect.Space.Whale

However another Korean app works great: https://play.google.com/store/apps/details?id=com.nflygame
Not sure where is the issue.

I am getting quite a lot of these errors, for 85 tests got 21 broken, some other broken Ids for testing the issue:
`a7yaha.com,
a333036.ldg,
a4l.maxm.droid,
aapkibazaar.com,
aapankhabariya.com,
aadviktech.com.erecharge,
a3labgo.tusar.narayanganjtrain,
aadhar.bluetree.in.verifyaadhar`

Found similar issues already opened, but they were targetting any id within similar query, where this one is region-specific only error.

Thanks. Miko.

**Comment by miki3475** [comment]
That was my mistake. The script works great, I just missed the fact some of the apps **don't have any similar** recommendation, therefore it returns error as it supposed.
