### ISSUE TITLE
Error requesting Google Play:unable to get local issuer certificate

### ISSUE THREAD

**Issue by praveens96** [facundoolano/google-play-scraper#449]
* Operating System: docker 
* Node version: 10.15.0
* google-play-scraper version: 8.0.2/latest

### Description: 
Describe your issue here
getting below message in production aws containers:

```
{
    "statuscode": 500,
    "statusText": "",
    "message": "Error requesting Google Play:unable to get local issuer certificate",
    "stackHighlighted": "Error: Error requesting Google Play:unable to get local issuer certificate\n    at /usr/src/app/node_modules/google-play-scraper/lib/utils/request.js:44:19\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
}
```
### Example code:
```js
NA
// Put code to reproduce the issue here
```

### Error message:

```
Put error message here
```

**Comment by MohamedAmineDahwathi** [comment]
Hello,

Any updates on this issue ?

Thanks,

**Comment by facundoolano** [comment]
Issue automatically closed. Please create a new one if the issue persists
