### ISSUE TITLE
Unexpected token in JSON with suggested example code

### ISSUE THREAD

**Issue by adibacco** [facundoolano/google-play-scraper#455]
* Operating System: Win10
* Node version: v12.13.1
* google-play-scraper version: 8.0.2

### Description: 
Describe your issue here

I get an exception with the example suggested on NPM page. 

### Example code:
```js
var gplay = require('google-play-scraper');

gplay.app({appId: 'com.google.android.apps.translate'})
  .then(console.log, console.log);
```

### Error message:

```
SyntaxError: Unexpected token , in JSON at position 6038
    at JSON.parse (<anonymous>)
    at C:\Users\adiba\Documents\programming\play-scraper\node_modules\google-play-scraper\lib\utils\scriptData.js:48:26
    at Array.reduce (<anonymous>)
    at parse (C:\Users\adiba\Documents\programming\play-scraper\node_modules\google-play-scraper\lib\utils\scriptData.js:42:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

**Comment by icarcal** [comment]
@adibacco I just tried here with version 8.0.2 and the return was ok for me.

Can you check if you are using the 8.0.2 version of the lib?

**Comment by adibacco** [comment]
Sorry, don't know why but I was using an old version (7.1.3)
