### ISSUE TITLE
The collection topselling_free is invalid for the given category, top apps or new apps

### ISSUE THREAD

**Issue by cac-dean** [facundoolano/google-play-scraper#488]
* Operating System: macOs
* Node version: v12.13.1
* google-play-scraper version: 8.0.4

### Description: 
sometimes , i will get "The collection topselling_free is invalid for the given category, top apps or new apps" error, but sometimes is be fine.

### Example code:
```js
const gplay = require('google-play-scraper');
const fs = require('fs');
const categorys = [gplay.category.APPLICATION, gplay.category.BUSINESS, gplay.category.LIFESTYLE, gplay.category.SOCIAL];

categorys.forEach(category => {
    if(fs.existsSync(category + '.json')){
        fs.unlinkSync(category + '.json');
    }
    
    gplay.list({
        country: 'tw',
        lang: 'zh-tw',
        category: category,
        num: 500
      })
      .then(
        apps => {

            if(apps && apps.length > 0){
                let data = JSON.stringify(apps);

                if(data.length > 0){
                    fs.writeFileSync(category + '.json', data);
                }
            }
        },
        error => {
            console.log(error);
        }
    ).catch(
        error => {
            console.log(error);
        }
    );
});
```

### Error message:

```
Error: The collection topselling_free is invalid for the given category, top apps or new apps
    at getParsedCluster (/Users/n/node_modules/google-play-scraper/lib/utils/parseCategoryApps.js:51:11)
    at parseCategoryApps (/Users/n/node_modules/google-play-scraper/lib/utils/parseCategoryApps.js:71:22)
    at /Users/n/node_modules/google-play-scraper/lib/list.js:29:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by 99zikke** [comment]
@cac-dean Hi, I have the same problem. Have you fixed it now?

**Comment by andrew-curry** [comment]
i have the same question,anyone has any ideas?

**Comment by Panda2Chan** [comment]
same where

**Comment by DorAmram** [comment]
Same question

**Comment by YakobovLior** [comment]
I'm also facing this issue.
Is there any way to list the 500 top free applications (without mentioning category)?

Thanks in advance

**Comment by facundoolano** [comment]
can you check if this still happens with the latest version?

**Comment by facundoolano** [comment]
closing as duplicate of #549
