### ISSUE TITLE
Crash on mapping app details

### ISSUE THREAD

**Issue by Aliaksandr-Kasko-JazzTeam** [facundoolano/google-play-scraper#496]
* Operating System: Windows/Linux
* Node version: 16.0.8
* google-play-scraper version: 8.0.4

### Description: 
Library crashes on mapping app details

### Example code:
```js
const gplay = require('google-play-scraper');
//...
const app = await gplay.app({
    appId: id,
    country: store
});
```

### Error message:

```
TypeError: Cannot read property 'replace' of undefined at Object.descriptionText [as fun] (/workspace/node_modules/google-play-scraper/lib/mappers/details.js:125:51)
at /workspace/node_modules/google-play-scraper/lib/utils/scriptData.js:52:19
at XWrap.f (/workspace/node_modules/ramda/dist/ramda.js:5955:28)
at XWrap.@@transducer/step (/workspace/node_modules/ramda/dist/ramda.js:392:25)
at _arrayReduce (/workspace/node_modules/ramda/dist/ramda.js:5137:46)
at _reduce (/workspace/node_modules/ramda/dist/ramda.js:5167:24)
at map (/workspace/node_modules/ramda/dist/ramda.js:5954:20)
at /workspace/node_modules/ramda/dist/ramda.js:586:23
at Object.f2 [as map] (/workspace/node_modules/ramda/dist/ramda.js:473:22)
at extractFields (/workspace/node_modules/google-play-scraper/lib/utils/scriptData.js:40:14)
```

**Comment by Aliaksandr-Kasko-JazzTeam** [comment]
Seems that it's applicable only for this 3 countries: kr, tw, hk

**Comment by skochy** [comment]
I'm also seeing a similar error:

```
HttpsError: TypeError: Cannot read property 'replace' of undefined
    at Object.getError (/workspace/lib/helpers/util.js:164:12)
    at /workspace/lib/endpoints/scraper_api.js:26:26
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ScraperApi.scrapeGame (/workspace/lib/endpoints/scraper_api.js:22:16)
```

and

```
Error: not found similar link
    at /workspace/node_modules/google-play-scraper/lib/similar.js:37:17
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ScraperApi.similarTo (/workspace/lib/endpoints/scraper_api.js:61:22)
```

**Comment by ansoncen** [comment]
> Seems that it's applicable only for these 3 countries: kr, tw, hk

the play store website has been changed to the new version in these three regions. The parser function is no longer valid for the new version of the website.

**Comment by Aliaksandr-Kasko-JazzTeam** [comment]
@facundoolano ping

**Comment by icarcal** [comment]
I believe the #498 PR also fixes this issue

**Comment by adrien1251** [comment]
Hello, 
Will you create a new version on npm today? 

Sincerely.

**Comment by facundoolano** [comment]
I won't be around a computer for a couple of weeks so no new npm version until then, you can just use the github commit in your package.json in the meantime

**Comment by adrien1251** [comment]
Thanks for your answer, how can we use the commit in the json package? 
Cause i use it like that in my package json : 
`"dependencies": {
    "google-play-scraper": "^8.0.4"
}`
Can i put a commit number instead ? 
`"dependencies": {
    "google-play-scraper": "commit-number"
}`

**Comment by ruimateus** [comment]
@adrien1251 

"google-play-scraper": "github:facundoolano/google-play-scraper"

works for me

**Comment by adrien1251** [comment]
Thank you for your reactivity ! :D

**Comment by adrien1251** [comment]
Hi guys, 
It would be just to know when you plan to update the lib on the npm side because, on my side putting the config in the json package as follows 
`"google-play-scraper": "github:facundoolano/google-play-scraper"`, my build takes 1h30 to be done.  It's good for a "quick" fix but not long term :s 

Thanks a lot! :)

**Comment by eldhosejoys** [comment]
Kindly update it on npm.

**Comment by facundoolano** [comment]
> I won't be around a computer for a couple of weeks so no new npm version until then, you can just use the github commit in your package.json in the meantime

**Comment by dhung1308** [comment]
> 

I getting error when using github commit : 
Error: Error requesting Google Play:connect ECONNREFUSED 127.0.0.1:443

Anyone help me fix it ?

**Comment by Primokorn** [comment]
I updated using **sudo npm install -g npm** then I read this thread.
I use your tool for several years and I didn't have any package.json so I downloaded the file and I edited the dependencies as suggested:

```
   "dependencies": {
    "cheerio": "^0.22.0",
    "debug": "^2.2.0",
    "eslint": "^5.16.0",
    "memoizee": "^0.4.11",
    "ramda": "^0.21.0",
    "got": "^11.8.3",
    "google-play-scraper": "github:facundoolano/google-play-scraper"
  },
```
I still have the same issue. Can someone explain with more information? Thanks.
`arnaud@L340-15IRH:~/AndroidAll/Google_Play_Scraper$ node getPic.js 
TypeError: Cannot read property 'replace' of undefined
    at Object.descriptionText [as fun] (/home/arnaud/AndroidAll/Google_Play_Scraper/node_modules/google-play-scraper/lib/mappers/details.js:125:51)
    at R.map (/home/arnaud/AndroidAll/Google_Play_Scraper/node_modules/google-play-scraper/lib/utils/scriptData.js:52:19)
    at XWrap.f (/home/arnaud/AndroidAll/Google_Play_Scraper/node_modules/ramda/dist/ramda.js:5955:28)
    at XWrap.@@transducer/step (/home/arnaud/AndroidAll/Google_Play_Scraper/node_modules/ramda/dist/ramda.js:392:25)
    at _arrayReduce (/home/arnaud/AndroidAll/Google_Play_Scraper/node_modules/ramda/dist/ramda.js:5137:46)
    at _reduce (/home/arnaud/AndroidAll/Google_Play_Scraper/node_modules/ramda/dist/ramda.js:5167:24)
    at map (/home/arnaud/AndroidAll/Google_Play_Scraper/node_modules/ramda/dist/ramda.js:5954:20)
    at /home/arnaud/AndroidAll/Google_Play_Scraper/node_modules/ramda/dist/ramda.js:586:23
    at Object.f2 [as map] (/home/arnaud/AndroidAll/Google_Play_Scraper/node_modules/ramda/dist/ramda.js:473:22)
    at extractFields (/home/arnaud/AndroidAll/Google_Play_Scraper/node_modules/google-play-scraper/lib/utils/scriptData.js:40:14)
arnaud@L340-15IRH:~/AndroidAll/Google_Play_Scraper$ 
`
KDE Neon User Edition 64bits.

**Comment by Primokorn** [comment]
I updated nodejs to v16.13.1 and installed this tool from scratch (I had it for a while and I had no package.json file at the root of the directory).
In which file do you write the instructions? Example:
`var gplay = require('google-play-scraper');

gplay.app({appId: 'com.google.android.apps.translate'})
  .then(console.log, console.log);`
And how to run it?
I just want to download app icons from several apps in one go. Thank you.
_KDE Neon User Edition 64bits_

**Comment by berrybar** [comment]
> #498 PR도 이 문제를 해결 한다고 생각합니다 [.](https://github.com/facundoolano/google-play-scraper/pull/498)

I ran it, but it doesn't work.
Is it impossible to bring kr rank??

**Comment by berrybar** [comment]
> I believe the #498 PR also fixes this issue


I ran it, but it doesn't work.
Is it impossible to bring kr rank??

**Comment by 13389203735** [comment]
> > 好像只适用于这三个国家：kr, tw, hk
> 
> 这三个地区的 Play 商店网站已更改为新版本。解析器功能对新版网站不再有效。



> > Seems that it's applicable only for these 3 countries: kr, tw, hk
> 
> the play store website has been changed to the new version in these three regions. The parser function is no longer valid for the new version of the website.

How to deal with this problem

**Comment by a2kas** [comment]
please update npm package

**Comment by hmzisb** [comment]
Same with github too. Please fix it.

**Comment by facundoolano** [comment]
I just published a new version of the package. Closing this issue, let me now if the problem persists.

**Comment by Aliaksandr-Kasko-JazzTeam** [comment]
@facundoolano still facing this issue for mentioned above kr, hk and tw stores

**Comment by facundoolano** [comment]
The kr error is a different issue, see #495
