### ISSUE TITLE
google play scrape error TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by gitRedgieGravador** [facundoolano/google-play-scraper#499]
* Operating System: Windows
* Node version: 14.17.0
* google-play-scraper version: 8.0.4

### Example code:
```js
gplay.app({ appId: 'com.anasamhs.gardenmatch' }).then((res) => {
        console.log(res)
    })
```

### Error message:

```
google play scrape error TypeError: Cannot read property 'replace' of undefined
    at Object.descriptionText [as fun] (/home/jonathan/axonite/axonite-scala-bridge/node_modules/google-play-scraper/lib/app.js:182:50)
    at R.map (/home/jonathan/axonite/axonite-scala-bridge/node_modules/google-play-scraper/lib/app.js:176:17)
    at XWrap.f (/home/jonathan/axonite/axonite-scala-bridge/node_modules/ramda/dist/ramda.js:5955:28)
    at XWrap.@@transducer/step (/home/jonathan/axonite/axonite-scala-bridge/node_modules/ramda/dist/ramda.js:392:25)
    at _arrayReduce (/home/jonathan/axonite/axonite-scala-bridge/node_modules/ramda/dist/ramda.js:5137:46)
    at _reduce (/home/jonathan/axonite/axonite-scala-bridge/node_modules/ramda/dist/ramda.js:5167:24)
    at map (/home/jonathan/axonite/axonite-scala-bridge/node_modules/ramda/dist/ramda.js:5954:20)
    at /home/jonathan/axonite/axonite-scala-bridge/node_modules/ramda/dist/ramda.js:586:23
    at Object.f2 [as map] (/home/jonathan/axonite/axonite-scala-bridge/node_modules/ramda/dist/ramda.js:473:22)
    at extractFields (/home/jonathan/axonite/axonite-scala-bridge/node_modules/google-play-scraper/lib/app.js:170:12)

```

**Comment by icarcal** [comment]
Hey @gitRedgieGravador I believe this PR #498 fixes this issue and it's already merged.
Needs only publish on npm

**Comment by gitRedgieGravador** [comment]
@icarcal thanks.. few minutes ago I was able to see the update you've done thanks a lot I will be waiting for the npm to be published.

**Comment by 1004885516** [comment]
When will NPM be released
