### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by asher-y-ma** [facundoolano/google-play-scraper#500]
TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.descriptionText [as fun] (/root/asher/node_modules/google-play-scraper/lib/mappers/details.js:125:51)
    at /root/asher/node_modules/google-play-scraper/lib/utils/scriptData.js:52:19
    at XWrap.f (/root/asher/node_modules/ramda/dist/ramda.js:5955:28)
    at XWrap.@@transducer/step (/root/asher/node_modules/ramda/dist/ramda.js:392:25)
    at _arrayReduce (/root/asher/node_modules/ramda/dist/ramda.js:5137:46)
    at _reduce (/root/asher/node_modules/ramda/dist/ramda.js:5167:24)
    at map (/root/asher/node_modules/ramda/dist/ramda.js:5954:20)
    at /root/asher/node_modules/ramda/dist/ramda.js:586:23
    at Object.f2 [as map] (/root/asher/node_modules/ramda/dist/ramda.js:473:22)
    at extractFields (/root/asher/node_modules/google-play-scraper/lib/utils/scriptData.js:40:14)

**Comment by adrien1251** [comment]
Hello, i think you need to look at this issue : https://github.com/facundoolano/google-play-scraper/issues/496
The resolution is in the end ;)

**Comment by dhung1308** [comment]
How to  update  module in heroku ? I still get this error

**Comment by asher-y-ma** [comment]
> Hello, i think you need to look at this issue : #496 The resolution is in the end ;)

thanks
