### ISSUE TITLE
Method app fails on every tested application.

### ISSUE THREAD

**Issue by jiristepan** [facundoolano/google-play-scraper#501]
* Operating System: Debian under WSL
* Node version: v14.8.1
* google-play-scraper version: 8.0.4

### Description: 
Method *app* fails on every tested application. Even with sample code.
Other methods (reviews etc.) are working.

### Example code:
```js
var gplay = require('google-play-scraper');

gplay.app({appId: 'com.google.android.apps.translate'})
  .then(console.log, console.log);
```

### Error message:
```
TypeError: Cannot read property 'replace' of undefined
    at Object.descriptionText [as fun] (/mnt/d/activate/code/data-team/SKODA/MSP/GCP/tests/node_modules/google-play-scraper/lib/mappers/details.js:125:51)
    at /mnt/d/activate/code/data-team/SKODA/MSP/GCP/tests/node_modules/google-play-scraper/lib/utils/scriptData.js:52:19
    at XWrap.f (/mnt/d/activate/code/data-team/SKODA/MSP/GCP/tests/node_modules/ramda/dist/ramda.js:5955:28)
    at XWrap.@@transducer/step (/mnt/d/activate/code/data-team/SKODA/MSP/GCP/tests/node_modules/ramda/dist/ramda.js:392:25)
    at _arrayReduce (/mnt/d/activate/code/data-team/SKODA/MSP/GCP/tests/node_modules/ramda/dist/ramda.js:5137:46)
    at _reduce (/mnt/d/activate/code/data-team/SKODA/MSP/GCP/tests/node_modules/ramda/dist/ramda.js:5167:24)
    at map (/mnt/d/activate/code/data-team/SKODA/MSP/GCP/tests/node_modules/ramda/dist/ramda.js:5954:20)
    at /mnt/d/activate/code/data-team/SKODA/MSP/GCP/tests/node_modules/ramda/dist/ramda.js:586:23
    at Object.f2 [as map] (/mnt/d/activate/code/data-team/SKODA/MSP/GCP/tests/node_modules/ramda/dist/ramda.js:473:22)
    at extractFields (/mnt/d/activate/code/data-team/SKODA/MSP/GCP/tests/node_modules/google-play-scraper/lib/utils/scriptData.js:40:14)
```

**Comment by jiristepan** [comment]
It looks like duplicate of https://github.com/facundoolano/google-play-scraper/issues/496

It can be resolved by adding module dependency from github instead from npm.
