### ISSUE TITLE
Error: Error requesting Google Play:Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by nottoobad** [facundoolano/google-play-scraper#503]
* Operating System:Windows 10
* Node version:10.15.0
* google-play-scraper version:github latest

### Description: 
Import 'https-proxy-agent' will cause 'google-play-scraper' throw the exception: Error: Error requesting Google Play:Cannot read property 'startsWith' of undefined

### Example code:
```js
// Put code to reproduce the issue here
var HttpsProxyAgent = require('https-proxy-agent'); //comment this line, code below will work.
var gplay = require('google-play-scraper');
gplay.app({appId: 'cc.pacer.androidapp'})
  .then(console.log, console.log);
```

### Error message:

```
{ Error: Error requesting Google Play:Cannot read property 'startsWith' of undefined
    at D:\google-play-scraper-pg\node_modules\google-play-scraper\lib\utils\request.js:41:19
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3) status: undefined }
```

**Comment by VitaliyRDev** [comment]
Check this instruction: https://github.com/sindresorhus/got/blob/main/documentation/tips.md#proxying

**Comment by facundoolano** [comment]
If I recall correctly you can pass a `requestOptions` field to all the methods. This is passed over to the underlying request library, currently got: [check this for proxy support](https://github.com/sindresorhus/got/blob/main/documentation/tips.md#proxying).

If you figure out an example please share here.

**Comment by facundoolano** [comment]
Issue automatically closed. Please create a new one if the issue persists
