### ISSUE TITLE
Document that node.js 8.x is not enough for 8.1.x

### ISSUE THREAD

**Issue by marxsk** [facundoolano/google-play-scraper#517]
Previously, it was possible to run library on top of the nodejs 8.x, now you have to upgrade node. What is fine but should be mentioned somewhere. 

Problem is using of generator functions [ function* (url, options) ] used in pirates module. Again, it is fine to no longer support obsolete versions :) But this issue may help someone in similar situation. 

```
(node:1698) UnhandledPromiseRejectionWarning: /home/vps/appscraper/node_modules/got/dist/source/create.js:157
const paginateEach = (async function* (url, options) {
^

SyntaxError: Unexpected token *
at createScript (vm.js:80:10)
at Object.runInThisContext (vm.js:139:10)
at Module._compile (module.js:617:28)
at Module._compile (/home/vps/appscraper/node_modules/pirates/lib/index.js:99:24)
at Module._extensions..js (module.js:664:10)
at Object.newLoader [as .js] (/home/vps/appscraper/node_modules/pirates/lib/index.js:104:7)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)
at Module.require (module.js:597:17)
(node:1698) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1698) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1731) UnhandledPromiseRejectionWarning: /home/vps/appscraper/node_modules/got/dist/source/create.js:157
const paginateEach = (async function* (url, options) {
^
```

**Comment by facundoolano** [comment]
Issue automatically closed. Please create a new one if the issue persists
