### ISSUE TITLE
Number of results

### ISSUE THREAD

**Issue by Chaepica** [facundoolano/google-play-scraper#527]
Does anyone have a problem when searching for applications through "search"? It gives me no more than 49 results, despite the fact that "num" is set to 250.

**Comment by facundoolano** [comment]
Can you give sample code of how this fails? Seems to work on a basic test for me:

``` 
g.search({term: "panda", num:220}).then((l) => console.log(l.map((a) => a.title)))
Promise {
  <pending>,
  [Symbol(async_id_symbol)]: 21097,
  [Symbol(trigger_async_id_symbol)]: 21096,
  [Symbol(destroyed)]: { destroyed: false }
}
> [
  'Panda Express',
  "Dr. Panda Town - Let's Create!",
  'Bubble Shooter: Panda Pop!',
  'Dr. Panda Restaurant 3',
  'Panda Gamepad Pro (BETA)',
  'Baby Panda Care',
  'Video Compressor Panda Resizer',
  "Baby Panda's Supermarket",
  'Pandalive - Video Chat',
  'HungryPanda: Food Delivery',
  'Panda Dome Antivirus and VPN | Panda Security',
  "Little Panda's Chinese Recipes",
  'Bored Panda',
  'Dr. Panda - Learn & Play',
  'Dr. Panda Town: Vacation',
  'PandaVPN Pro - Easy To Use',
  'foodpanda: Food & Groceries',
  "Little Panda's Restaurant",
  'Baby Panda World',
  'Panda Lu Treehouse',
  'Dr. Panda Trucks',
  'Little Panda Policeman',
  'Dr. Panda Town: Pet World',
  'Dr. Panda Town: Mall',
  'Baby Panda Home Safety',
  'Taichi Panda',
  'Baby Panda: Care for animals',
  "Baby Panda's Fashion Dress Up",
  'Talking Panda',
  "Baby Panda's School Bus",
  'Panda Remit',
  "Little Panda's Space Kitchen",
  "Little Panda's Pet Salon",
  'PandaVPN Lite - Easy To Use',
  'Dr. Panda Daycare',
  'Baby Panda Care 2',
  "Little Panda's Town: My World",
  'Panda Pro Helper Adviser',
  "Baby Panda's Town: My Dream",
  'Dr. Panda World',
  'Panda Lu & Friends - Playground Fun with Baby Pets',
  'Panda Lu Baby Bear Care 2 - Babysitting & Daycare',
  'Dr. Panda Mailman',
  'Dr. Panda Plus: Home Designer',
  'Little Panda Hotel Manager',
  'Baby Panda’s Ice Cream Shop',
  'Talking Baby Panda - Kids Game',
  'Dr. Panda Home',
  'Baby Panda’s Summer: Café',
  'Panda Run',
  'Panda Run',
  'Dr. Panda Mailman',
  'Little Panda: Princess Makeup',
  "Little Panda's Ice Cream Bars",
  'Baby Panda Earthquake Safety 1',
  'Dr. Panda School',
  "Baby Panda's City",
  'Little Panda’s Jewel Adventure',
  "Baby Panda's Playhouse",
  'Professor Panda',
  'Panda Wallpapers',
  "Little Panda's Farm",
  'Dr. Panda Plus: Home Designer',
  "Baby Panda's Carnival",
  "Baby Panda's Airport",
  "Baby Panda's Daily Life",
  "Little Panda's Dream Castle",
  'Dr. Panda Restaurant 2',
  "Little Panda's Bakery Story",
  "Little Panda's Sushi Kitchen",
  "Little Panda's Hero Battle",
  "Baby Panda's Ice Cream Truck",
  'Baby Panda Car Racing',
  "Baby Panda's Emergency Tips",
  "Baby Panda's Color Mixing",
  'Baby Panda Happy Clean',
  "Dr. Panda & Toto's Treehouse",
  'Panda Lu Fun Park - Amusement Rides & Pet Friends',
  "Baby Panda' s House Cleaning",
  'My Baby Panda Chef',
  "Little Panda's Snack Factory",
  "Baby Panda's Breakfast Cooking",
  'Swap-Swap Panda',
  "Little Panda's Food Cooking",
  'Panda Lu Baby Bear City - Pet Babysitting & Care',
  'Dr. Panda Restaurant',
  "Baby Panda's Food Party",
  'Little Panda: Dinosaur Care',
  "Baby Panda's Town: Life",
  "Little Panda's Flowers DIY",
  "Little Panda's Candy Shop",
  'Panda Evolution: Idle Clicker',
  'panda player',
  'Python Pandas',
  'Baby Panda: Cooking Party',
  'Baby Panda Gets Organized',
  'Panda Bubble Shooter',
  'Rewards Panda Play & Earn',
  '3 Pandas in Japan : Adventure Puzzle Game',
  'Baby Panda’s Potty Training',
  ... 120 more items
```

**Comment by sonyvivek** [comment]
Hi,
Here below is  sample code when we include full detail flag as true. it throws error
gplay.search({term: "panda", fullDetail: true, num:250}).then((l) => console.log(l.map((a) => a.title)))

If we change num value to 48 or 49 it will work. If value is more than that it throws the  error.

(node:16552) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at Object.descriptionText [as fun] (D:\Code\scrap\node_modules\google-play-scraper\lib\mappers\details.js:104:51)
    at D:\Code\scrap\node_modules\google-play-scraper\lib\utils\scriptData.js:52:19
    at XWrap.f (D:\Code\scrap\node_modules\ramda\dist\ramda.js:5955:28)
    at XWrap.@@transducer/step (D:\Code\scrap\node_modules\ramda\dist\ramda.js:392:25)
    at _arrayReduce (D:\Code\scrap\node_modules\ramda\dist\ramda.js:5137:46)
    at _reduce (D:\Code\scrap\node_modules\ramda\dist\ramda.js:5167:24)
    at map (D:\Code\scrap\node_modules\ramda\dist\ramda.js:5954:20)
    at D:\Code\scrap\node_modules\ramda\dist\ramda.js:586:23
    at Object.f2 [as map] (D:\Code\scrap\node_modules\ramda\dist\ramda.js:473:22)
    at extractFields (D:\Code\scrap\node_modules\google-play-scraper\lib\utils\scriptData.js:40:14)

**Comment by wendellkuci** [comment]
I have the same problem:  I get a max of 30 results ever

**Comment by facundoolano** [comment]
Issue automatically closed. Please create a new one if the issue persists
