### ISSUE TITLE
Error requesting Google Play: While fetching suggestions

### ISSUE THREAD

**Issue by ghost** [facundoolano/google-play-scraper#537]
* Operating System: Win 10
* Node version: v14.17.5
* google-play-scraper version: 8.1.0

### Description: 
Whenever trying to get suggestion from google play it is returning 

Error: Error requesting Google Play:
    at D:\101logix\PROTHEME\protheme1\app analysis\api\node_modules\aso\node_modules\google-play-scraper\lib\utils\request.js:44:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  status: 503
}

### Example code:
```js
function getSuggestionFromAppStore(req, res){
    return new Promise( async (resolve, reject)=>{
        var appname = req.body.name
        try{
            store.suggest({
                term: appname
            }).then(res=>{
                
                return resolve({"success":true, "data":res});
            }).catch(err=>{
                console.log(err)
                return reject({"success":false, "error":"Error Occured"});
            })
        }catch(err){
            return reject({"success":false, "error":"Error Occured"});
        }
    })
}
```

### Error message:

```
Error: Error requesting Google Play:
    at D:\101logix\PROTHEME\protheme1\app analysis\api\node_modules\aso\node_modules\google-play-scraper\lib\utils\request.js:44:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  status: 503
}
```
![image](https://user-images.githubusercontent.com/36229073/166095467-28d4ef91-289f-418a-9db9-9ca3f977d4b0.png)

**Comment by facundoolano** [comment]
can you check if this still happens with the latest version?

**Comment by facundoolano** [comment]
Issue automatically closed. Please create a new one if the issue persists
