### ISSUE TITLE
[Bug] search: "Showing results for" error

### ISSUE THREAD

**Issue by KaKi87** [facundoolano/google-play-scraper#566]
* Operating System: Linux Mint 19.3
* Node version: 16.15.1
* google-play-scraper version: 9.0.0

### Description: 
A `Showing results for` error is thrown when using `search` with a typo.

### Example code:
```js
require('google-play-scraper')
    .search({ term: 'runing tracker' })
    .then(console.log)
    .catch(console.error);
```

### Error message:
```
Error: Showing results for 
    at processFirstPage (node_modules/google-play-scraper/lib/search.js:103:13)
    at node_modules/google-play-scraper/lib/search.js:31:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Additional info:
This is probably related to the following screenshot.
![Screenshot from 2022-06-28 10-04-28](https://user-images.githubusercontent.com/21284089/176127933-a450c69c-1882-4574-b8b3-d17230bc4aea.png)

---
Thanks

**Comment by shaindi** [comment]
I came across this bug too.
The "Showing results for" section have to be considered in the mapping.
I Don't know how to fix.

**Comment by facundoolano** [comment]
I published a patch yesterday, can you try again?

**Comment by facundoolano** [comment]
Issue automatically closed. Please create a new one if the issue persists
