### ISSUE TITLE
Still facing crashing when getting app details for [kr, tw, hk] markets

### ISSUE THREAD

**Issue by Aliaksandr-K-JazzTeam** [facundoolano/google-play-scraper#567]
* Operating System: node16-alpine Docker Image
* Node version: 16.x
* google-play-scraper version: 9.0.1

### Example code:
```js
const app = await gplay.app({
  appId: "com.moo.ssulmo.ssulmo",
  country: "kr"
});
```

### Error message:
First error on descriptionText
```
TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.descriptionText [as fun] (/app/node_modules/google-play-scraper/lib/utils/mappingHelpers.js:6:51)
    at /app/node_modules/google-play-scraper/lib/utils/scriptData.js:52:19
    at XWrap.f (/app/node_modules/ramda/dist/ramda.js:5955:28)
    at XWrap.@@transducer/step (/app/node_modules/ramda/dist/ramda.js:392:25)
    at _arrayReduce (/app/node_modules/ramda/dist/ramda.js:5137:46)
    at _reduce (/app/node_modules/ramda/dist/ramda.js:5167:24)
    at map (/app/node_modules/ramda/dist/ramda.js:5954:20)
    at /app/node_modules/ramda/dist/ramda.js:586:23
    at Object.f2 [as map] (/app/node_modules/ramda/dist/ramda.js:473:22)
    at extractFields (/app/node_modules/google-play-scraper/lib/utils/scriptData.js:40:14)
```
If I add nullsafe to description like this
`function descriptionText (description = '') {`
then I got an error in another place:
```
TypeError: Cannot read properties of undefined (reading 'split')
    at Object.fun (app/node_modules/google-play-scraper/lib/app.js:97:29)
    at app/node_modules/google-play-scraper/lib/utils/scriptData.js:52:19
    at XWrap.f (app/node_modules/ramda/dist/ramda.js:5955:28)
    at XWrap.@@transducer/step (app/node_modules/ramda/dist/ramda.js:392:25)
    at _arrayReduce (app/node_modules/ramda/dist/ramda.js:5137:46)
    at _reduce (app/node_modules/ramda/dist/ramda.js:5167:24)
    at map (app/node_modules/ramda/dist/ramda.js:5954:20)
    at app/node_modules/ramda/dist/ramda.js:586:23
    at Object.f2 [as map] (app/node_modules/ramda/dist/ramda.js:473:22)
    at extractFields (app/node_modules/google-play-scraper/lib/utils/scriptData.js:40:14)
```
But here I can't find a quick fix anymore.

Maybe there's some mismatch with mappings for these markets

**Comment by knirpsfass** [comment]
seems like the data key for the app is `ds:5` instead of `ds:4`

**Comment by Aliaksandr-Kasko-JazzTeam** [comment]
UPD. I also found that it affects on `th` and `au` markets.

**Comment by knirpsfass** [comment]
@Aliaksandr-Kasko-JazzTeam i've opened #572 but i still need to test it and also fix the family genre mapping

**Comment by Aliaksandr-Kasko-JazzTeam** [comment]
@knirpsfass for now I can confirm that for th market your PR works fine

**Comment by facundoolano** [comment]
Issue automatically closed. Please create a new one if the issue persists
