### ISSUE TITLE
Similar is not working

### ISSUE THREAD

**Issue by josepius-clemson** [facundoolano/google-play-scraper#576]
* Operating System: Windows 10
* Node version: v16.13.2
* google-play-scraper version: 9.0.2

### Description: 
Similar function is returning the following error:

### Example code:
```js
var gplay = require('google-play-scraper');
gplay.similar({appId: 'com.google.android.apps.translate'})
  .then(console.log, console.log);
```

### Error message:

```
Error: Error requesting Google Play:getaddrinfo ENOTFOUND play.google.comundefined&gl=us&hl=en
    at c:\..\node_modules\google-play-scraper\lib\utils\request.js:41:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: undefined
}
```

**Comment by gianlucascoccia** [comment]
Is this working now? I get this error, no matter which app I try:

```
Error: Similar link not found
    at parseSimilarApps (/Users/gianlucascoccia/Desktop/store_scraper/node_modules/google-play-scraper/lib/parsers/parseSimilarApps.js:20:11)
    at /Users/gianlucascoccia/Desktop/store_scraper/node_modules/google-play-scraper/lib/similar.js:38:29
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by srikanthlogic** [comment]
Works for me, both in `9.1.1` and in `master`.

**Comment by muzzyrost** [comment]
- Operating System: Ubuntu
- Node version: 16.16.0
- google-play-scraper version: 9.1.1

Example code:
```
var gplay = require('google-play-scraper');
gplay.similar({appId: 'com.google.android.apps.translate'}).then(console.log, console.log);
```
Error message:
```
TypeError: Cannot read properties of null (reading 'length')
at parseSimilarApps (/home/ub/node_modules/google-play-scraper/lib/similar.js:68:16)
at /node_modules/google-play-scraper/lib/similar.js:40:29
at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**Comment by facundoolano** [comment]
Issue automatically closed. Please create a new one if the issue persists
