### ISSUE TITLE
EVENT PAID LIST returning  error

### ISSUE THREAD

**Issue by josepius-clemson** [facundoolano/google-play-scraper#579]
* Operating System: Windows 10
* Node version: v16.13.2
* google-play-scraper version:9.02

### Description: 
Describe your issue here

### Example code:
```js
var gplay = require('google-play-scraper');

gplay.list({
    category: gplay.category.EVENTS,
    collection: gplay.collection.TOP_PAID,
    num: 1000
  })
  .then(console.log, console.log);
```

### Error message:
TypeError: Cannot read properties of undefined (reading 'map')
    at c:\..\node_modules\ramda\dist\ramda.js:578:31
    at Object.f2 [as map] (c:\..\node_modules\ramda\dist\ramda.js:473:22)
    at parseCollectionApps (c:\..\node_modules\google-play-scraper\lib\list.js:121:27)
    at c:\..\node_modules\google-play-scraper\lib\list.js:51:33
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
Put error message here
```

**Comment by yussufbiyik** [comment]
I have the same issue, a fix pls?

**Comment by facundoolano** [comment]
Issue automatically closed. Please create a new one if the issue persists
