### ISSUE TITLE
Cannot read property 'replace' of undefined, mapping issue

### ISSUE THREAD

**Issue by dave-filion** [facundoolano/google-play-scraper#582]
Looks like there may have been another change to the GPlay data structure, seeing consistent errors since earlier today when calling to get info on various apps:
```
Aug 18 00:21:36 node[867]: TypeError: Cannot read property 'replace' of undefined
Aug 18 00:21:36 node[867]:     at Object.descriptionText [as fun] (/.../node_modules/google-play-scraper/lib/utils/mappingHelpers.js:6:51)
Aug 18 00:21:36 node[867]:     at /.../node_modules/google-play-scraper/lib/utils/scriptData.js:52:19
Aug 18 00:21:36 node[867]:     at XWrap.f (/.../node_modules/ramda/dist/ramda.js:5955:28)
```

Guessing the `descriptionText` field might be missing?

**Comment by YairLeviMevorach** [comment]
I fix it
https://github.com/facundoolano/google-play-scraper/pull/583

**Comment by dave-filion** [comment]
Awesome thank you!

**Comment by cf211** [comment]
@YairLeviMevorach 
i still see this error , how can i fix it?
`Aug 18 00:21:36 node[867]: TypeError: Cannot read property 'replace' of undefined
Aug 18 00:21:36 node[867]:     at Object.descriptionText [as fun] (/.../node_modules/google-play-scraper/lib/utils/mappingHelpers.js:6:51)
Aug 18 00:21:36 node[867]:     at /.../node_modules/google-play-scraper/lib/utils/scriptData.js:52:19
Aug 18 00:21:36 node[867]:     at XWrap.f (/.../node_modules/ramda/dist/ramda.js:5955:28)`

the following github actions failed. Maybe deploy not yet?
https://github.com/facundoolano/google-play-scraper/actions/runs/2883376349

**Comment by Aliaksandr-Kasko-JazzTeam** [comment]
@facundoolano when #583 will be released on npm?

**Comment by denisRay** [comment]
@facundoolano waiting for release in the npm :)

**Comment by sergeyrepko** [comment]
this solution did not help me solve the problem

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/80681063/185903511-10b788c6-3642-47d7-bed2-4724049ce2af.png">

**Comment by xeinebiu** [comment]
I can confirm the issue is not fixed.

**Comment by facundoolano** [comment]
Issue automatically closed. Please create a new one if the issue persists
