### ISSUE TITLE
app is not working

### ISSUE THREAD

**Issue by potstip** [facundoolano/google-play-scraper#589]
* Operating System: w10
* Node version: 18.7
* google-play-scraper version: 9.1.0

### Description: 
After latest update app is not working

### Example code:
```js
var gplay = require('google-play-scraper');

gplay.app({appId: 'com.google.android.apps.translate'})
  .then(console.log, console.log);
```

### Error message:

```
TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.descriptionText [as fun] (C:\Users\potstip\node_modules\google-play-scraper\lib\utils\mappingHelpers.js:6:51)
    at C:\Users\potstip\node_modules\google-play-scraper\lib\utils\scriptData.js:52:19
    at XWrap.f (C:\Users\potstip\node_modules\ramda\dist\ramda.js:5955:28)
    at XWrap.@@transducer/step (C:\Users\potstip\node_modules\ramda\dist\ramda.js:392:25)
    at _arrayReduce (C:\Users\potstip\node_modules\ramda\dist\ramda.js:5137:46)
    at _reduce (C:\Users\potstip\node_modules\ramda\dist\ramda.js:5167:24)
    at map (C:\Users\potstip\node_modules\ramda\dist\ramda.js:5954:20)
    at C:\Users\potstip\node_modules\ramda\dist\ramda.js:586:23
    at Object.f2 [as map] (C:\Users\potstip\node_modules\ramda\dist\ramda.js:473:22)
    at extractFields (C:\Users\potstip\node_modules\google-play-scraper\lib\utils\scriptData.js:40:14)
```

**Comment by potstip** [comment]
Master branch is working fine.

**Comment by cf211** [comment]
9.1.1 is working

**Comment by facundoolano** [comment]
Issue automatically closed. Please create a new one if the issue persists
