### ISSUE TITLE
working randomly?

### ISSUE THREAD

**Issue by ChayaGel** [facundoolano/google-play-scraper#601]
seems it  started to works randomly,
sometimes works and sometimes not,
(what I saw, mainly in Hebrew words - its not working, but dont know if the language is the point or something else)

---
full error message:
TypeError: Cannot read properties of undefined (reading 'map')
     at D:\...\google-play-search\node_modules\ramda\dist\ramda.js:578:31
     at Object.f2 [as map] (D:\...\google-play-search\node_modules\ramda\dist\ramda.js:473:22)
     at processFirstPage (D:\...\google-play-search\node_modules\google-play-scraper\lib\search.js:101:27)
     at D:\...\google-play-search\node_modules\google-play-scraper\lib\search.js:31:21
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by ChayaGel** [comment]
duplicate with #596
