### ISSUE TITLE
Unable to get AppDetails by using google-play-api

### ISSUE THREAD

**Issue by developer-swetabh** [facundoolano/google-play-scraper#640]
* Operating System: Windows 10
* Node version: 18.16.0
* google-play-scraper version: 6.2.3

### Description: 
I was trying to use the google-play-api, but unable to get the appDetails of any application.

### Example code:
```js
gplay.app({appId: 'com.google.android.apps.translate'})
  .then(console.log, console.log);
```

### Error message:
```
Cannot read properties of undefined (reading 'replace')
```

Upon closely inspecting the code and adding console log, this is what I am getting:

```
TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.descriptionText [as fun] (C:\Users\ssuman\Binaries\Swetabh\google-play-api\node_modules\google-play-scraper\lib\utils\mappingHelpers.js:9:51)
    at C:\Users\ssuman\Binaries\Swetabh\google-play-api\node_modules\google-play-scraper\lib\utils\scriptData.js:52:19
    at XWrap.f (C:\Users\ssuman\Binaries\Swetabh\google-play-api\node_modules\ramda\dist\ramda.js:5955:28)
    at XWrap.@@transducer/step (C:\Users\ssuman\Binaries\Swetabh\google-play-api\node_modules\ramda\dist\ramda.js:392:25)
    at _arrayReduce (C:\Users\ssuman\Binaries\Swetabh\google-play-api\node_modules\ramda\dist\ramda.js:5137:46)
    at _reduce (C:\Users\ssuman\Binaries\Swetabh\google-play-api\node_modules\ramda\dist\ramda.js:5167:24)
    at map (C:\Users\ssuman\Binaries\Swetabh\google-play-api\node_modules\ramda\dist\ramda.js:5954:20)
    at C:\Users\ssuman\Binaries\Swetabh\google-play-api\node_modules\ramda\dist\ramda.js:586:23
    at Object.f2 [as map] (C:\Users\ssuman\Binaries\Swetabh\google-play-api\node_modules\ramda\dist\ramda.js:473:22)
    at extractFields (C:\Users\ssuman\Binaries\Swetabh\google-play-api\node_modules\google-play-scraper\lib\utils\scriptData.js:40:14)
```

**Comment by facundoolano** [comment]
Issue automatically closed. Please create a new one if the issue persists
