### ISSUE TITLE
IP problem

### ISSUE THREAD

**Issue by Zexiong-Xiang** [facundoolano/google-play-scraper#665]
* Operating System:
* Node version:
* google-play-scraper version:

### Description: 
Now, I installed dependencies, Run the demo, Try switching IP proxies, But it always times out or the read fails, and I think there is a problem with the request of the source code itself.

### Example code:
```
import gplay from "google-play-scraper";

gplay.list({
    category: gplay.category.GAME_ACTION,
    collection: gplay.collection.TOP_FREE,
    num: 2
  })
  .then(console.log, console.log);
```

### Error message:

```
[Running] node "c:\Users\axiong\PycharmProjects\Privacy_Policy\10.12\index.js"
Error: Error requesting Google Play:connect ETIMEDOUT 142.251.42.238:443
    at request (file:///c:/Users/axiong/node_modules/google-play-scraper/lib/utils/request.js:40:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  status: undefined
}
[Done] exited with code=0 in 21.704 seconds
```
Or
```
[Running] node "c:\Users\axiong\PycharmProjects\Privacy_Policy\10.12\index.js"
Error: Error requesting Google Play:read ECONNRESET
    at request (file:///c:/Users/axiong/node_modules/google-play-scraper/lib/utils/request.js:40:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  status: undefined
}
[Done] exited with code=0 in 15.788 seconds
```

**Comment by walrus543** [comment]
I had this issue some times ago: https://github.com/facundoolano/google-play-scraper/issues/400#issuecomment-625848506
And it's back...

````
Error: connect ETIMEDOUT 2607:f8b0:4006:80e::2016:443
        at createConnectionError (node:net:1646:14)
        at afterConnectMultiple (node:net:1676:16) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '2607:f8b0:4006:80e::2016',
      port: 443
    }
```` 
I switched to different IPs/countries via ProtonVPN. I can download a few icons then the downloads are hanging.
Without ProtonVPN, I can't download anything.

**Comment by facundoolano** [comment]
Issue automatically closed. Please create a new one if the issue persists
